// Frases de dominio ES→EN (se fusionan en runtime-translator.ts)
export const DOMAIN_PHRASES: Record<string, string> = {
  'correo de contacto': 'contact email',
  'correo electronico del cliente': 'customer email',
  'correo del cliente': 'customer email',
  'correo de la empresa': 'company email',
  'correo de facturacion': 'billing email',
  'correo de notificacion': 'notification email',
  'correo de confirmacion': 'confirmation email',
  'correo de confirmacion de la cuenta': 'account confirmation email',
  'correo de confirmacion de cuenta creada': 'account created confirmation email',
  'correo de confirmacion de la cuenta creada': 'account created confirmation email',
  'correo de verificacion': 'verification email',
  'correo de bienvenida': 'welcome email',
  'correo de recuperacion': 'recovery email',
  'correo de restablecimiento': 'reset email',
  'email de contacto': 'contact email',
  'telefono de contacto': 'contact phone',
  'telefono de la empresa': 'company phone',
  'numero de telefono': 'phone number',
  'numero de celular': 'mobile number',
  'direccion de correo': 'email address',
  'direccion de correo electronico': 'email address',
  'direccion de la empresa': 'company address',
  'direccion de facturacion': 'billing address',
  'direccion de envio': 'shipping address',
  'direccion de entrega': 'delivery address',
  'licencia vigente': 'active license',
  'licencia activa': 'active license',
  'licencia expirada': 'expired license',
  'licencia de prueba': 'trial license',
  'plan vigente': 'current plan',
  'plan activo': 'active plan',
  'plan mensual': 'monthly plan',
  'plan trimestral': 'quarterly plan',
  'plan semestral': 'semi-annual plan',
  'plan anual': 'annual plan',
  'estado de la licencia': 'license status',
  'fecha de expiracion': 'expiration date',
  'fecha de vencimiento': 'due date',
  'dias de prueba': 'trial days',
  'periodo de prueba': 'trial period',
  'usuario en prueba': 'trial user',
  'usuarios en prueba': 'trial users',
  'usuario en trial': 'trial user',
  'usuarios en trial': 'trial users',
  'dias restantes': 'days remaining',
  'dia restante': 'day remaining',
  'sin limite': 'unlimited',
  'con limite': 'limited',
  'ocurrio un error': 'an error occurred',
  'ocurrio un error al': 'an error occurred while',
  'ocurrio un error al cargar': 'an error occurred while loading',
  'error al cargar': 'error loading',
  'error al guardar': 'error saving',
  'error al crear': 'error creating',
  'error al eliminar': 'error deleting',
  'error al enviar': 'error sending',
  'error al actualizar': 'error updating',
  'error al procesar': 'error processing',
  'error al conectar': 'error connecting',
  'error de conexion': 'connection error',
  'error interno': 'internal error',
  'error interno del servidor': 'internal server error',
  'error inesperado': 'unexpected error',
  'error desconocido': 'unknown error',
  'se produjo un error': 'an error occurred',
  'se produjo un error inesperado': 'an unexpected error occurred',
  'intente nuevamente': 'try again',
  'intente de nuevo': 'try again',
  'vuelva a intentar': 'try again',
  'por favor intente nuevamente': 'please try again',
  'por favor intente de nuevo': 'please try again',
  'recargue la pagina': 'reload the page',
  'contacte a soporte': 'contact support',
  'contacte con soporte': 'contact support',
  'contacte con el administrador': 'contact the administrator',
  'si el problema persiste': 'if the problem persists',
  'si el problema continua': 'if the problem continues',
  'el servicio no esta disponible': 'the service is not available',
  'el servicio del sri no esta disponible': 'the SRI service is not available',
  'el servicio del sri no esta disponible en este momento': 'the SRI service is not available at this time',
  'complete los datos manualmente': 'fill in the data manually',
  'consulta ruc': 'RUC lookup',
  'consultar ruc': 'look up RUC',
  'datos del ruc': 'RUC data',
  'datos cargados desde el sri': 'data loaded from the SRI',
  'datos de prueba': 'test data',
  'verifique con el sri': 'check with the SRI',
  'datos del contribuyente': 'taxpayer data',
  'razon social': 'business name',
  'nombre comercial': 'trade name',
  'nombre de la empresa': 'company name',
  'nombre de la compania': 'company name',
  'numero de ruc': 'RUC number',
  'obligado a llevar contabilidad': 'required to keep accounting records',
  'agente de retencion': 'withholding agent',
  'contribuyente especial': 'special taxpayer',
  'contribuyente rimpe': 'RIMPE taxpayer',
  'regimen rimpe': 'RIMPE regime',
  'tipo de contribuyente': 'taxpayer type',
  'actividad economica': 'economic activity',
  'actividades economicas': 'economic activities',
  'sujeto pasivo': 'taxable person',
  'contribuyente': 'taxpayer',
  'contribuyentes': 'taxpayers',
  'numero de autorizacion': 'authorization number',
  'fecha de autorizacion': 'authorization date',
  'clave de acceso': 'access key',
  'claves de acceso': 'access keys',
  'punto de emision': 'issue point',
  'puntos de emision': 'issue points',
  'codigo de establecimiento': 'establishment code',
  'codigo punto de emision': 'issue point code',
  'tipo de emision': 'issue type',
  'emision normal': 'normal issue',
  'emision en contingencia': 'contingency issue',
  'emision electronica': 'electronic issue',
  'factura electronica': 'electronic invoice',
  'facturas electronicas': 'electronic invoices',
  'comprobante electronico': 'electronic voucher',
  'comprobantes electronicos': 'electronic vouchers',
  'facturacion electronica': 'electronic invoicing',
  'firma electronica': 'digital signature',
  'firmas electronicas': 'digital signatures',
  'firma digital': 'digital signature',
  'certificado digital': 'digital certificate',
  'certificado electronico': 'electronic certificate',
  'firma electronica valida': 'valid digital signature',
  'firma electronica invalida': 'invalid digital signature',
  'firma electronica expirada': 'expired digital signature',
  'sin firma electronica': 'no digital signature',
  'firma registrada': 'signature registered',
  'firma registrada en el servidor': 'signature registered on the server',
  'cargar firma': 'upload signature',
  'cargar firma electronica': 'upload digital signature',
  'subir firma': 'upload signature',
  'subir firma electronica': 'upload digital signature',
  'subir logo': 'upload logo',
  'cargar logo': 'upload logo',
  'eliminar firma': 'delete signature',
  'eliminar logo': 'delete logo',
  'contrasena de la firma': 'signature password',
  'contrasena de la firma electronica': 'digital signature password',
  'contrasena incorrecta para la firma electronica': 'incorrect password for the digital signature',
  'la contrasena no corresponde a la firma': 'the password does not match the signature',
  'la contrasena no corresponde a la firma electronica': 'the password does not match the digital signature',
  'analisis de virus': 'virus scan',
  'analisis de archivos': 'file scan',
  'estado de los motores': 'engine status',
  'no disponible': 'not available',
  'antivirus local': 'local antivirus',
  'analisis de archivos en la nube': 'cloud file scan',
  'sistema de archivos': 'file system',
  'archivo de prueba': 'test file',
  'datos limpios': 'clean data',
  'prueba de virus': 'virus test',
  'motor de analisis': 'scan engine',
  'motores de analisis': 'scan engines',
  'servidor local': 'local server',
  'servidor remoto': 'remote server',
  'base de datos': 'database',
  'bases de datos': 'databases',
  'usuario de prueba': 'test user',
  'usuario creado': 'created user',
  'usuario creado correctamente': 'user created successfully',
  'usuario creado exitosamente': 'user created successfully',
  'cuenta creada': 'account created',
  'cuenta creada exitosamente': 'account created successfully',
  'cuenta creada correctamente': 'account created successfully',
  'bienvenido de vuelta': 'welcome back',
  'bienvenido': 'welcome',
  'bienvenida': 'welcome',
  'iniciar sesion': 'sign in',
  'inicio de sesion': 'sign in',
  'cerrar sesion': 'sign out',
  'crear cuenta': 'create account',
  'crear una cuenta': 'create an account',
  'registrarse': 'sign up',
  'crear cuenta nueva': 'create new account',
  'olvido su contrasena': 'forgot your password',
  'recuperar contrasena': 'recover password',
  'restablecer contrasena': 'reset password',
  'cambiar contrasena': 'change password',
  'confirmar contrasena': 'confirm password',
  'nueva contrasena': 'new password',
  'contrasena actual': 'current password',
  'requisitos de contrasena': 'password requirements',
  'minimo 8 caracteres': 'minimum 8 characters',
  'al menos una letra mayuscula': 'at least one uppercase letter',
  'al menos una letra minuscula': 'at least one lowercase letter',
  'al menos un numero': 'at least one number',
  'al menos un simbolo especial': 'at least one special symbol',
  'sesion expirada': 'session expired',
  'la sesion ha expirado': 'the session has expired',
  'por favor inicie sesion': 'please sign in',
  'por favor inicie sesion nuevamente': 'please sign in again',
  'debe iniciar sesion': 'you must sign in',
  'necesita iniciar sesion': 'you need to sign in',
  'enviar factura': 'send invoice',
  'enviar factura al sri': 'send invoice to SRI',
  'enviar al sri': 'send to SRI',
  'enviado al sri': 'sent to SRI',
  'enviada al sri': 'sent to SRI',
  'enviados al sri': 'sent to SRI',
  'enviadas al sri': 'sent to SRI',
  'se envio al sri': 'sent to SRI',
  'enviar correo': 'send email',
  'enviar por correo': 'send by email',
  'enviar por email': 'send by email',
  'enviar por whatsapp': 'send via WhatsApp',
  'correo enviado': 'email sent',
  'correo enviado correctamente': 'email sent successfully',
  'correo enviado exitosamente': 'email sent successfully',
  'no se pudo enviar el correo': 'could not send the email',
  'no se pudo enviar la factura': 'could not send the invoice',
  'no se pudo enviar al sri': 'could not send to SRI',
  'no se pudo enviar el mensaje': 'could not send the message',
  'se envio un correo': 'an email was sent',
  'se ha enviado un correo': 'an email has been sent',
  'revise su correo': 'check your email',
  'revise su bandeja de entrada': 'check your inbox',
  'verifique su correo': 'check your email',
  'usuario registrado': 'registered user',
  'usuarios registrados': 'registered users',
  'usuario registrado correctamente': 'user registered successfully',
  'registro exitoso': 'registration successful',
  'usuario creado con exito': 'user created successfully',
  'proceso exitoso': 'successful process',
  'operacion exitosa': 'operation successful',
  'operacion completada': 'operation completed',
  'la operacion se completo': 'the operation was completed',
  'la operacion se realizo': 'the operation was carried out',
  'la operacion se realizo correctamente': 'the operation was completed successfully',
  'operacion realizada': 'operation completed',
  'operacion realizada correctamente': 'operation completed successfully',
  'operacion realizada exitosamente': 'operation completed successfully',
  'operacion completada exitosamente': 'operation completed successfully',
  'proceso completado': 'process completed',
  'proceso completado correctamente': 'process completed successfully',
  'proceso completado exitosamente': 'process completed successfully',
  'se completo correctamente': 'completed successfully',
  'se completo exitosamente': 'completed successfully',
  'se ha completado': 'has been completed',
  'se ha completado correctamente': 'has been completed successfully',
  'se ha completado exitosamente': 'has been completed successfully',
  'se realizo correctamente': 'was completed successfully',
  'se realizo exitosamente': 'was completed successfully',
  'se guardo correctamente': 'was saved successfully',
  'se guardo exitosamente': 'was saved successfully',
  'se elimino correctamente': 'was deleted successfully',
  'se elimino exitosamente': 'was deleted successfully',
  'se actualizo correctamente': 'was updated successfully',
  'se actualizo exitosamente': 'was updated successfully',
  'se creo correctamente': 'was created successfully',
  'se creo exitosamente': 'was created successfully',
  'se envio correctamente': 'was sent successfully',
  'se envio exitosamente': 'was sent successfully',
  'se registro correctamente': 'was registered successfully',
  'se registro exitosamente': 'was registered successfully',
  'se genero correctamente': 'was generated successfully',
  'se genero exitosamente': 'was generated successfully',
  'se descargo correctamente': 'was downloaded successfully',
  'se subio correctamente': 'was uploaded successfully',
  'se importo correctamente': 'was imported successfully',
  'se exporto correctamente': 'was exported successfully',
  'se imprimio correctamente': 'was printed successfully',
  'se abrio correctamente': 'was opened successfully',
  'se cerro correctamente': 'was closed successfully',
  'se cancelo correctamente': 'was cancelled successfully',
  'se confirmo correctamente': 'was confirmed successfully',
  'se valido correctamente': 'was validated successfully',
  'se verifico correctamente': 'was verified successfully',
  'se firmo correctamente': 'was signed successfully',
  'se autorizo correctamente': 'was authorized successfully',
  'se aprobo correctamente': 'was approved successfully',
  'se rechazo correctamente': 'was rejected successfully',
  'se restauro correctamente': 'was restored successfully',
  'se restablecio correctamente': 'was reset successfully',
  'se reinicio correctamente': 'was restarted successfully',
  'se proceso correctamente': 'was processed successfully',
  'se proceso exitosamente': 'was processed successfully',
  'se completaron correctamente': 'were completed successfully',
  'se guardaron correctamente': 'were saved successfully',
  'se eliminaron correctamente': 'were deleted successfully',
  'se actualizaron correctamente': 'were updated successfully',
  'se crearon correctamente': 'were created successfully',
  'se enviaron correctamente': 'were sent successfully',
  'se registraron correctamente': 'were registered successfully',
  'se generaron correctamente': 'were generated successfully',
  'se importaron correctamente': 'were imported successfully',
  'se exportaron correctamente': 'were exported successfully',
  'se procesaron correctamente': 'were processed successfully',
  'los datos se guardaron correctamente': 'the data was saved successfully',
  'los datos se actualizaron correctamente': 'the data was updated successfully',
  'los datos se eliminaron correctamente': 'the data was deleted successfully',
  'los datos se cargaron correctamente': 'the data was loaded successfully',
  'los datos se procesaron correctamente': 'the data was processed successfully',
  'los cambios se guardaron correctamente': 'the changes were saved successfully',
  'los cambios se guardaron exitosamente': 'the changes were saved successfully',
  'la informacion se guardo correctamente': 'the information was saved successfully',
  'la informacion se actualizo correctamente': 'the information was updated successfully',
  'la informacion se elimino correctamente': 'the information was deleted successfully',
  'la informacion se proceso correctamente': 'the information was processed successfully',
  'el registro se guardo correctamente': 'the record was saved successfully',
  'el registro se actualizo correctamente': 'the record was updated successfully',
  'el registro se elimino correctamente': 'the record was deleted successfully',
  'el registro se creo correctamente': 'the record was created successfully',
  'el documento se guardo correctamente': 'the document was saved successfully',
  'el documento se elimino correctamente': 'the document was deleted successfully',
  'el documento se genero correctamente': 'the document was generated successfully',
  'el archivo se subio correctamente': 'the file was uploaded successfully',
  'el archivo se descargo correctamente': 'the file was downloaded successfully',
  'el archivo se elimino correctamente': 'the file was deleted successfully',
  'el archivo se guardo correctamente': 'the file was saved successfully',
  'el correo se envio correctamente': 'the email was sent successfully',
  'el correo se envio exitosamente': 'the email was sent successfully',
  'la factura se envio correctamente': 'the invoice was sent successfully',
  'la factura se envio exitosamente': 'the invoice was sent successfully',
  'la factura se firmo correctamente': 'the invoice was signed successfully',
  'la factura se firmo exitosamente': 'the invoice was signed successfully',
  'la factura se autorizo correctamente': 'the invoice was authorized successfully',
  'la factura se aprobo correctamente': 'the invoice was approved successfully',
  'la factura se envio al sri correctamente': 'the invoice was sent to SRI successfully',
  'el comprobante se firmo correctamente': 'the voucher was signed successfully',
  'el comprobante se envio correctamente': 'the voucher was sent successfully',
  'el comprobante se envio al sri correctamente': 'the voucher was sent to SRI successfully',
  'el comprobante se autorizo correctamente': 'the voucher was authorized successfully',
  'el comprobante se aprobo correctamente': 'the voucher was approved successfully',
  'la empresa se creo correctamente': 'the company was created successfully',
  'la empresa se creo exitosamente': 'the company was created successfully',
  'el cliente se creo correctamente': 'the customer was created successfully',
  'el producto se creo correctamente': 'the product was created successfully',
  'el proveedor se creo correctamente': 'the supplier was created successfully',
  'el empleado se creo correctamente': 'the employee was created successfully',
  'el usuario se creo correctamente': 'the user was created successfully',
  'la cuenta se creo correctamente': 'the account was created successfully',
  'la cuenta se creo exitosamente': 'the account was created successfully',
  'la cuenta se verifico correctamente': 'the account was verified successfully',
  'la cuenta se verifico exitosamente': 'the account was verified successfully',
  'la cuenta fue verificada': 'the account was verified',
  'la cuenta fue creada': 'the account was created',
  'la cuenta fue creada exitosamente': 'the account was created successfully',
  'la cuenta fue creada correctamente': 'the account was created successfully',
  'la cuenta fue verificada exitosamente': 'the account was verified successfully',
  'la cuenta fue verificada correctamente': 'the account was verified successfully',
  'verifique su correo electronico': 'check your email',
  'verifique su bandeja de entrada': 'check your inbox',
  'revise su correo electronico': 'check your email',
  'se ha enviado un correo de confirmacion': 'a confirmation email has been sent',
  'se ha enviado un correo a': 'an email has been sent to',
  'se enviara un correo de confirmacion': 'a confirmation email will be sent',
  'se enviara un correo a': 'an email will be sent to',
  'hemos enviado un correo': 'we have sent an email',
  'hemos enviado un correo de confirmacion': 'we have sent a confirmation email',
  'hemos enviado un correo a': 'we have sent an email to',
  'te hemos enviado un correo': 'we have sent you an email',
  'te hemos enviado un correo de confirmacion': 'we have sent you a confirmation email',
  'hemos enviado un correo de confirmacion a': 'we have sent a confirmation email to',
  'se le ha enviado un correo': 'an email has been sent to you',
  'se le enviara un correo': 'an email will be sent to you',
  'se le enviara un correo de confirmacion': 'a confirmation email will be sent to you',
  'se le enviara un correo a': 'an email will be sent to you at',
  'revise su correo electronico para confirmar': 'check your email to confirm',
  'revise su correo para confirmar': 'check your email to confirm',
  'revise su bandeja de entrada para confirmar': 'check your inbox to confirm',
  'para confirmar su cuenta': 'to confirm your account',
  'para confirmar la cuenta': 'to confirm the account',
  'para verificar su cuenta': 'to verify your account',
  'para verificar la cuenta': 'to verify the account',
  'para activar su cuenta': 'to activate your account',
  'para activar la cuenta': 'to activate the account',
  'para completar el registro': 'to complete the registration',
  'para completar su registro': 'to complete your registration',
  'para completar el proceso': 'to complete the process',
  'para continuar': 'to continue',
  'para continuar usando': 'to continue using',
  'para continuar usando contaec': 'to continue using ContaEC',
  'para continuar con el proceso': 'to continue with the process',
  'para continuar con el registro': 'to continue with the registration',
  'para continuar con la compra': 'to continue with the purchase',
  'para continuar con el pago': 'to continue with the payment',
  'para acceder': 'to access',
  'para acceder al sistema': 'to access the system',
  'para acceder a la plataforma': 'to access the platform',
  'para acceder a su cuenta': 'to access your account',
  'para ingresar': 'to log in',
  'para ingresar al sistema': 'to log in to the system',
  'para poder': 'to be able to',
  'para poder acceder': 'to be able to access',
  'para poder usar': 'to be able to use',
  'para poder utilizar': 'to be able to use',
  'para poder continuar': 'to be able to continue',
  'para poder completar': 'to be able to complete',
  'para poder facturar': 'to be able to invoice',
  'para poder emitir': 'to be able to issue',
  'para poder emitir comprobantes': 'to be able to issue vouchers',
  'para poder emitir facturas': 'to be able to issue invoices',
  'para poder enviar': 'to be able to send',
  'para poder enviar facturas': 'to be able to send invoices',
  'para poder enviar comprobantes': 'to be able to send vouchers',
  'para poder generar': 'to be able to generate',
  'para poder generar facturas': 'to be able to generate invoices',
  'para poder generar comprobantes': 'to be able to generate vouchers',
  'para poder imprimir': 'to be able to print',
  'para poder descargar': 'to be able to download',
  'para poder subir': 'to be able to upload',
  'para poder guardar': 'to be able to save',
  'para poder registrar': 'to be able to register',
  'para poder crear': 'to be able to create',
  'para poder crear la empresa': 'to be able to create the company',
  'para poder crear una empresa': 'to be able to create a company',
  'para poder crear su empresa': 'to be able to create your company',
  'para poder crear facturas': 'to be able to create invoices',
  'para poder crear comprobantes': 'to be able to create vouchers',
  'para poder crear una factura': 'to be able to create an invoice',
  'para poder crear una proforma': 'to be able to create a proforma',
  'para poder crear un comprobante': 'to be able to create a voucher',
  'para poder crear un cliente': 'to be able to create a customer',
  'para poder crear un producto': 'to be able to create a product',
  'para poder crear un proveedor': 'to be able to create a supplier',
  'para poder crear un empleado': 'to be able to create an employee',
  'para poder crear un usuario': 'to be able to create a user',
  'para poder continuar usando contaec': 'to be able to continue using ContaEC',
  'para poder continuar con el proceso': 'to be able to continue with the process',
  'para poder continuar con la compra': 'to be able to continue with the purchase',
  'para poder continuar con el pago': 'to be able to continue with the payment',
  'para poder continuar con la facturacion': 'to be able to continue with the invoicing',
  'para poder continuar con la emision': 'to be able to continue with the issue',
  'para poder continuar con la emision de comprobantes': 'to be able to continue issuing vouchers',
  'para poder continuar emitiendo': 'to be able to continue issuing',
  'para poder continuar emitiendo comprobantes': 'to be able to continue issuing vouchers',
  'para poder continuar emitiendo facturas': 'to be able to continue issuing invoices',
  'para poder seguir': 'to be able to continue',
  'para poder seguir usando': 'to be able to continue using',
  'para poder seguir usando contaec': 'to be able to continue using ContaEC',
  'para poder seguir facturando': 'to be able to continue invoicing',
  'para poder seguir emitiendo': 'to be able to continue issuing',
  'para poder seguir emitiendo comprobantes': 'to be able to continue issuing vouchers',
  'para poder seguir emitiendo facturas': 'to be able to continue issuing invoices',
  'para poder seguir usando el sistema': 'to be able to continue using the system',
  'para poder seguir usando la plataforma': 'to be able to continue using the platform',
  'para poder seguir usando la aplicacion': 'to be able to continue using the application',
  'para poder seguir usando el programa': 'to be able to continue using the program',
};
